my-server-host: 47.102.101.181
server:
  port: 8282
spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: core-service-api-route
          uri: lb://core-service-api
          predicates:
            - Path=/core/**
          filters:
            - StripPrefix=1
        #==============================
        - id: authc-service-api-route
          uri: lb://authority-app
          predicates:
            - Path=/authc/**

    nacos:
      discovery:
        server-addr: ${my-server-host}:8848
